version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
    - $PWD/hack/ddl_device_registry.sql:/docker-entrypoint-initdb.d/ddl_device_registry.sql
  mqtt-bridge:
    image: quay.io/infinimesh/mqtt-bridge:latest
    ports:
      - "8081:8081"
    volumes:
      - $PWD/hack/server.crt:/server.crt
      - $PWD/hack/server.key:/server.key
    environment:
      - KAFKA_HOST=kafka:29092
      - DEVICE_REGISTRY_URL=device-registry:8080
    depends_on:
      - kafka
    restart: unless-stopped
  device-registry:
    image: quay.io/infinimesh/device-registry:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_ADDR=postgresql://postgres@postgres:5432/test?sslmode=disable
    restart: unless-stopped
  shadow-delta-merger:
    image: quay.io/infinimesh/shadow-delta-merger:latest
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka:29092
    restart: unless-stopped
  shadow-api:
    image: quay.io/infinimesh/shadow-api:latest
    ports:
      - "8085:8085"
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka:29092
      - KAFKA_TOPIC=private.changelog.reported-state
    restart: unless-stopped

