version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: infinimesh
      RABBITMQ_DEFAULT_PASS: infinimesh
  mqtt-bridge:
    image: ghcr.io/infinimesh/infinimesh/mqtt-bridge:latest
    restart: unless-stopped
    ports:
      - "1883:1883" # BasicAuth(non-TLS)
      - "8883:8883" # Standard(TLS)
    volumes:
      - $PWD/hack/server.crt:/cert/tls.crt
      - $PWD/hack/server.key:/cert/tls.key
    environment:
      DEBUG: "true"
      RABBITMQ_CONN: amqp://infinimesh:infinimesh@rabbitmq:5672/
      DEVICE_REGISTRY_URL: repo:8080
      SIGNING_KEY: "${SIGNING_KEY}"
    depends_on:
      - kafka
    links:
      - kafka
  telemetry-router:
    image: ghcr.io/infinimesh/infinimesh/telemetry-router:latest
    environment:
      KAFKA_HOST: kafka:29092
    depends_on:
      - kafka
    restart: unless-stopped
  shadow-delta-merger:
    image: ghcr.io/infinimesh/infinimesh/shadow-delta-merger:latest
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka:29092
    restart: unless-stopped
  shadow-api:
    restart: unless-stopped
    image: ghcr.io/infinimesh/infinimesh/shadow-api:latest
    ports:
      - "8096:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka:29092
      DB_ADDR: redis:6379
  shadow-persister:
    restart: unless-stopped
    image: ghcr.io/infinimesh/infinimesh/shadow-persister:latest
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka:29092
      DB_ADDR: redis:6379

  repo:
    image: ghcr.io/infinimesh/infinimesh/repo:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db:8529
      DB_CRED: root:openSesame
      SHADOW_HOST: shadow-api:8080
      SIGNING_KEY: "${SIGNING_KEY}"
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  db:
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: openSesame
    ports:
      - 8529:8529
    volumes:
      - data:/var/lib/arangodb3

volumes:
  data:
