version: "3.2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mqtt-bridge:
    image: ghcr.io/slntopp/infinimesh/mqtt-bridge:latest
    restart: unless-stopped
    ports:
      - "8090:8080" # BasicAuth(non-TLS)
      - "8089:8089" # Standard(TLS)
    volumes:
      - $PWD/hack/server.crt:/cert/tls.crt
      - $PWD/hack/server.key:/cert/tls.key
    environment:
      DEBUG: "true"
      KAFKA_HOST: kafka:29092
      DEVICE_REGISTRY_URL: device-registry:8080
    depends_on:
      - kafka
    links:
      - kafka
      - repo:device-registry
  telemetry-router:
    image: ghcr.io/slntopp/infinimesh/telemetry-router:latest
    environment:
      KAFKA_HOST: kafka:29092
    depends_on:
      - kafka
    restart: unless-stopped
  shadow-delta-merger:
    image: ghcr.io/slntopp/infinimesh/shadow-delta-merger:latest
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka:29092
    restart: unless-stopped
  shadow-api:
    restart: unless-stopped
    image: ghcr.io/slntopp/infinimesh/shadow-api:latest
    ports:
      - "8096:8096"
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka:29092
      DB_ADDR: redis:6379
  shadow-persister:
    restart: unless-stopped
    image: ghcr.io/slntopp/infinimesh/shadow-persister:latest
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka:29092
      DB_ADDR: redis:6379
  frontend:
    image: ghcr.io/slntopp/infinimesh/frontend:latest
    ports:
      - "80:80"
    environment:
      APISERVER_URL: http://apiserver-rest:8081

  repo:
    image: ghcr.io/slntopp/infinimesh/repo:latest
    restart: unless-stopped
    depends_on:
      - alpha
    environment:
      DB_HOST: db:8529
      DB_CRED: root:openSesame
      SHADOW_HOST: shadow-api:8080
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  db:
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: openSesame
    ports:
      - 8529:8529
    volumes:
      - data:/var/lib/arangodb3

volumes:
  data:
