version: "3.2"
services:
  
  web:
    image: ghcr.io/infinimesh/infinimesh/web:latest
    restart: always
    depends_on:
      - repo
    ports:
      - "8000:8000"
    environment:
      APISERVER_HOST: repo:8080

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"

  mqtt-bridge:
    image: ghcr.io/infinimesh/infinimesh/mqtt-bridge:latest
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - repo
    ports:
      - "1883:1883" # BasicAuth(non-TLS)
      - "8883:8883" # Standard(TLS)
    volumes:
      - $PWD/hack/server.crt:/cert/tls.crt
      - $PWD/hack/server.key:/cert/tls.key
    environment:
      DEBUG: "true"
      RABBITMQ_CONN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      DEVICE_REGISTRY_URL: repo:8080
      SIGNING_KEY: "${SIGNING_KEY}"

  repo:
    image: ghcr.io/infinimesh/infinimesh/repo:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db:8529
      DB_CRED: root:openSesame
      SHADOW_HOST: shadow:8080
      SIGNING_KEY: "${SIGNING_KEY}"
  shadow:
    image: ghcr.io/infinimesh/infinimesh/shadow:latest
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      RABBITMQ_CONN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      REDIS_HOST: redis:6379
      
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  db:
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: openSesame
    ports:
      - 8529:8529
    volumes:
      - data:/var/lib/arangodb3

volumes:
  data:
