version: '2'

tasks:
  lint:
    cmds:
      - golangci-lint run
  build:
    cmds:
      - go install ./...
    env:
      GO111MODULE: on
  test:
    cmds:
      - go test ./...
  default:
    cmds:
      - task: build
