version: '2.2'

tasks:
  debug-mqtt-send:
    env:
      PORT: 8089
    cmds:
      - go run hack/mqtt_testclients/produce/produce.go -broker localhost:$PORT
  proto:
    cmds:
      - prototool generate
  lint:
    cmds:
      - golangci-lint run
  build:
    cmds:
      - go install ./...
    env:
      GO111MODULE: on
  test:
    cmds:
      - go test ./...
  docker:
    silent: true
    cmds:
      - |
        set -e
        _root=$PWD
        cd ./Dockerfiles
        for f in *; do
          echo docker build -f $f/Dockerfile -t quay.io/infinimesh/$f:latest $_root
          docker build -f $f/Dockerfile -t quay.io/infinimesh/$f:latest $_root
        done
  default:
    cmds:
      - task: build
