version: '2.2'

tasks:
  debug-mqtt-send:
    desc: Send mqtt message to local broker
    env:
      PORT: 8089
    cmds:
      - go run hack/mqtt_testclients/produce/produce.go -broker localhost:$PORT
  proto:
    desc: Generate protobuf files
    cmds:
      - prototool generate
  generate-swagger:
    deps: [proto]
    cmds:
      - cp pkg/apiserver/apipb/api.swagger.json docs/swagger-ui/swagger.json
  lint:
    desc: Run linter
    cmds:
      - golangci-lint run
  build:
    desc: Perform full go build of all binaries
    cmds:
      - go install ./...
    env:
      GO111MODULE: on
  test:
    desc: Run tests
    cmds:
      - go test ./...
  docker:
    desc: Perform docker build for all Dockerfiles
    silent: true
    cmds:
      - |
        set -e
        _root=$PWD
        cd ./Dockerfiles
        for f in *; do
          echo docker build -f $f/Dockerfile -t quay.io/infinimesh/$f:latest $_root
          docker build -f $f/Dockerfile -t quay.io/infinimesh/$f:latest $_root &
        done
        wait
  default:
    cmds:
      - task: build
