version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/infinimesh/infinimesh
    steps:
      - setup_remote_docker
      - checkout
      - run: go mod verify
      - run: make build
