version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/infinimesh/infinimesh

    steps:
      - checkout
      - run:
          name: Verify go.mod
          command: go mod verify
      - run:
          name: Install Task
          command: curl -s https://taskfile.org/install.sh | sh
      - run:
          name: Install linters
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.11.2 && mv ./bin/* /go/bin/
      - run:
          name: Lint
          command: task lint
      - run:
          name: Run build
          command: task build
      - run:
          name: Run tests
          command: task test
  build-frontend:
    docker:
      - image: circleci/node:10.14.2
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: deps
          command: cd frontend && npm i
      - run:
          name: build
          command: cd frontend && npm run build
workflows:
  version: 2
  all:
    jobs:
      - build
      - build-frontend
