version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/infinimesh/infinimesh

    steps:
      - checkout
      - run:
          name: Verify go.mod
          command: go mod verify
      - run:
          name: Install linters
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.11.2 && mv ./bin/* /go/bin/
      - run:
          name: Lint
          command: golangci-lint run
      - run:
          name: Run build
          command: make build
