version: "3.8"
services:
  db:
    container_name: database-master
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - 8529:8529
    volumes:
      - data:/var/lib/arangodb3
    networks:
      - arangodb
  
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user
      - LDAP_PASSWORDS=password

networks:
  arangodb:
    driver: bridge

volumes:
  data:
