version: "3.8"
services:
  db:
    container_name: database-master
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - 8529:8529
    volumes:
      - data:/var/lib/arangodb3
    networks:
      - arangodb

networks:
  arangodb:
    driver: bridge

volumes:
  data:
