apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: my-platform-timescaledb
spec:
  version: "11.1-v1"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  terminationPolicy: DoNotTerminate
