name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set Docker up
        uses: docker-practice/actions-setup-docker@master

      - name: Compose Up
        run: docker-compose -f e2e/docker-compose.yaml up -d --quiet-pull

      - name: Run tests
        run: docker exec -it testrunner bash -c 'cd /go/src/github.com/slntopp/infinimesh && go mod download && CGO_ENABLED=0 go run -mod=mod hack/import_dgraph_sample_data.go -drop && go test -mod=mod ./...'
  
  tests-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        run: cd frontend && yarn

      - name: Run Linter
        run: cd frontend && yarn lint

      - name: Run Tests
        run: cd frontend && yarn test